### An Implementation Of Batch Gradient Descent With Early Stopping For Softmax Regression Without Using Scikit-learn

In [51]:
import numpy as np

In [65]:
def get_gradient_scalar(row, theta_matrix, output_class, true_outcome):
    '''return p_k^(i) hat - y_k^(i)'''
#     print(row)
#     print(output_class_theta)
#     print()
    
    relative_probabilities = row @ theta_matrix
    print(relative_probabilities)
    
    probability_hat = 0.0
    match_indicator = 1 if output_class == true_outcome else 0
    return probability_hat - match_indicator

In [66]:
def get_theta_gradient(output_class, X, y, theta_matrix):
    theta_gradient = np.zeros((1, X.shape[1]))
    
    

    for row, true_outcome in zip(X, y):
        theta_gradient += get_gradient_scalar(row, theta_matrix, output_class, true_outcome) * row
    
    return theta_gradient / X.shape[0]

In [67]:
def my_batch_GD(X, y, num_output_classes, alpha = 0.1):
    theta_matrix = np.random.rand(X[0].size, num_output_classes)
    m = X.shape[0]
    
    # delta_theta_matrix = np.zeros((X[0].size, num_output_classes))
    delta_theta_matrix = np.array([]).reshape((0, X.shape[1]))
    
    for i in range(num_output_classes):
#         delta_theta_matrix = np.append(delta_theta_matrix, np.array([[get_theta_gradient(i, X, y, theta_matrix)]]))
        delta_theta_matrix = np.vstack((delta_theta_matrix, np.array(get_theta_gradient(i, X, y, theta_matrix))))
    
#     print(delta_theta_matrix)
#     print()
#     print("transpose:\n", np.transpose(delta_theta_matrix))
#     print()
    theta_matrix += alpha * np.transpose(delta_theta_matrix)
    #     print(theta_matrix)
    return theta_matrix

In [68]:
print(my_batch_GD(np.array( [ [1,2,3], [4,5,6], [7,8,9], [10,11,12] ] ), np.array([0, 1, 1, 0]), 3))

[4.21836311 4.86823878 3.42064994]
[ 9.51859467 12.04294339  8.17588983]
[14.81882623 19.21764799 12.93112971]
[20.1190578 26.3923526 17.6863696]
[4.21836311 4.86823878 3.42064994]
[ 9.51859467 12.04294339  8.17588983]
[14.81882623 19.21764799 12.93112971]
[20.1190578 26.3923526 17.6863696]
[4.21836311 4.86823878 3.42064994]
[ 9.51859467 12.04294339  8.17588983]
[14.81882623 19.21764799 12.93112971]
[20.1190578 26.3923526 17.6863696]
[[-0.02395552  0.51187301  0.4046316 ]
 [ 0.25477949  0.4077198   0.52532675]
 [ 0.56091988  0.49697539  0.65512162]]


In [64]:
W = np.array([ -1, 0, 2 ])
X = np.array([ [1,-1,1], [2,2,2], [3,3,3] ])

W @ X

array([5, 7, 5])